language: php

php:
  - 7.0
  - 7.1

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache
    - "$HOME/.local"
    - mkdocs-theme

env:
  global:
    - SITE_URL: https://{PACKAGE_VENDOR}.github.io/{PACKAGE_NAME}
    - GH_USER_NAME: "{ORGANIZATION}"
    - GH_USER_EMAIL: jaap@polderknowledge.nl
    - GH_REF: github.com/{PACKAGE_VENDOR}/{PACKAGE_NAME}.git

matrix:
  include:
    - php: 7.0
      env:
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/polderknowledge/mkdocs-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then ./mkdocs-theme/deploy.sh ; fi

notifications:
  email: false
  irc: "irc.freenode.org#polderknowledge"
